// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an export has got to.
 *
 * The order is the order phases run in, and the phase *before* a long one is the useful signal:
 * a UI that shows "typesetting 4,245 pages" for 45 seconds is telling the truth, and one that
 * shows a spinner is not.
 */
export type ExportPhase = "Translating" | "ReadingAssets" | "Layout" | "Serializing" | "Done" | "Cancelled" | "Failed";
