// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The height model for unmeasured sections.
 *
 * Calibrated by measuring rendered sections in a real browser, not by reasoning
 * about CSS. See `GeometryCalibration::default` and `app/test/calibrate.ts`.
 *
 * The three derives serve one purpose: the frontend must not keep its own copy of
 * these numbers. `Serialize`/`Deserialize` carry them over the bridge, and `TS`
 * generates the TypeScript from this definition, so a rename cannot leave the
 * frontend reading a field that no longer exists. See `DOCTRINE.md` §8.
 *
 * # Why this exports to its own file
 *
 * `ts-rs` writes each `export` by *overwriting* its target, and this type is the
 * only one in this crate that needs generating. When both crates exported into a
 * single `generated-bridge.ts`, `cargo test` raced the two writers and the result
 * depended on which finished last: one run produced all seven types, the next
 * produced only this one, and every export test passed either way. Nothing
 * indicated a problem because nothing had failed.
 *
 * So the output paths are disjoint — this crate owns
 * `app/src/core/generated-calibration.ts`, the shell owns
 * `app/src/core/generated-bridge.ts` — and a `cargo test` run is idempotent.
 *
 * The attribute is still required. Without it `ts-rs` will not emit a definition
 * for a cross-crate dependency at all, and writes
 * `import type { GeometryCalibration } from ".../GeometryCalibration"` pointing at
 * a path that does not exist and never will. With it, the shell's generated file
 * carries a real `import` of a file that is really there.
 */
export type GeometryCalibration = { 
/**
 * Pixels per 100 characters of text.
 *
 * Linear in characters, not words: line breaking depends on characters per
 * line, so 2000 words of short words is taller than 2000 words of long ones.
 */
px_per_100_chars: number, 
/**
 * Pixels per paragraph.
 *
 * **Not optional.** A paragraph break costs a line even at zero characters.
 * A characters-only model fitted against real measurements gave a 30.6% mean
 * error and a 128% worst case, and reported a "chrome" of 320px against a CSS
 * truth of 58px — it was absorbing paragraph structure into the wrong
 * parameter. Adding this term took the mean error to 3.8% and the worst to
 * 15.8%.
 */
px_per_paragraph: number, 
/**
 * Fixed overhead per section: card padding plus the inter-section gap, which
 * exist whether or not there is any text.
 */
section_chrome_px: number, };
