// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeometryCalibration } from "./generated-calibration";

/**
 * What a backup produced.
 */
export type BackupReply = { 
/**
 * Where it was written.
 */
path: string, 
/**
 * Its size in bytes, so a UI can say "412 MB" rather than nothing.
 *
 * A JS `number`, not `bigint`: `ts-rs` emits `bigint` for any 64-bit integer unless
 * told otherwise, and a file size in bytes is a `number`. The same correction as
 * `ExportReply`'s timings, and the third time -- which is a sign the annotation belongs
 * somewhere shared rather than being re-derived per field.
 */
bytes: number, 
/**
 * Milliseconds, as a `number`: the same `u128`-to-`bigint` correction as `ExportReply`.
 */
elapsed_ms: number, 
/**
 * How many rows a snapshot of this kind carries, for a status line that wants to say
 * something more useful than a byte count.
 */
documents: number, sections: number, assets: number, };

/**
 * Everything the frontend needs for its first frame.
 *
 * Sent as **MessagePack**, not JSON. This payload carries the manifest plus the
 * content of every section near the caret; for a 2000-page document that is a few
 * hundred KB on the path to first paint, and JSON parse cost there is exactly what
 * the boot sequence is trying to avoid.
 *
 * Everything *after* boot is JSON, because those messages are small and being
 * able to read one in a log is worth more than the bytes.
 */
export type BootPayload = { document_id: string, title: string, 
/**
 * The height model, fitted by `app/test/calibrate.ts`. Shipped rather than
 * compiled into the frontend so there is one definition and the packaged app
 * cannot disagree with the measurements it was fitted from.
 */
calibration: GeometryCalibration, sections: Array<ManifestSection>, 
/**
 * Sections whose content is included. The rest of the document is manifest
 * rows only, which is what lets the scrollbar be correct before anything is
 * mounted.
 */
visible: Array<SectionContent>, 
/**
 * Where the caret was when the document was last closed, if known.
 */
focused_section_id: string | null, 
/**
 * Scroll offset to restore, in pixels. Null on first open.
 */
scroll_top: number | null, };

/**
 * What `commit_section_edit` did, and the counts it settled on.
 *
 * # Why the counts come back
 *
 * Because the caller supplied some of them and Rust recomputed the rest, and a caller
 * that cannot see the authoritative values will keep using its own. A section's
 * `block_count` drives its height estimate, so a frontend and a store that disagree
 * about it produce a scrollbar that is wrong for that section for the rest of the
 * session, with no error anywhere.
 *
 * Returning them makes the divergence visible at the moment it happens and lets the
 * caller correct its record rather than accumulate a quiet difference.
 */
export type CommitResponse = { section_id: string, 
/**
 * Row id in the write-ahead log, for diagnostics and for the WAL's own tests.
 *
 * `number`, not `bigint` — the same reason as `order_key`: an `i64` crossing
 * MessagePack arrives as a JS number inside 53 bits, which a row counter always is.
 */
wal_row_id: number, 
/**
 * Counts derived by `analyze` from the bytes actually written.
 */
word_count: number, char_count: number, block_count: number, 
/**
 * Echoed back rather than derived: `analyze` has no mark counter.
 */
mark_count: number, 
/**
 * Un-freed WAL rows for this document after this write.
 *
 * Reported because it is the number that says whether the WAL is being folded. A
 * frontend can watch it climb and knows something is wrong long before the file
 * does.
 */
pending: number, };

/**
 * One document in the open file, for a switcher.
 */
export type DocumentSummary = { id: string, title: string, 
/**
 * Section count, so the switcher can show size without a manifest read per row.
 */
sections: number, 
/**
 * Words, likewise.
 */
words: number, updated_at: number, };

/**
 * A throwaway document, built in the store for the verification harness.
 *
 * # Why this is a command and not a fixture
 *
 * The LRU bound is only meaningful against a document whose content lives in SQLite,
 * because that is the only case where dropping a section's bytes is *recoverable*. A
 * synthetic document supplied by the frontend has nothing to fetch from, so the cache
 * correctly declines to drop it — which is why the in-engine run could not exercise
 * the bound at all until this existed. The bound was Node-tested and in-engine
 * untested, and the two are not substitutes: the Node test proves the data structure
 * evicts, and only this proves the wiring does.
 *
 * # Why it is ephemeral
 *
 * It is built in the user's real database. Fifty sections of fixture prose left behind
 * by every cross-engine run would be litter next to real work, so the harness deletes
 * it with `delete_ephemeral_document` when it is done.
 */
export type EphemeralDocument = { document_id: string, section_ids: Array<string>, 
/**
 * Sections whose content the boot payload will carry, and how many there are in all.
 *
 * Both, so the harness can assert that the ones past the boot window really did
 * arrive without content. A test that cannot tell the two apart would pass against a
 * payload that carried everything.
 */
boot_visible: number, sections: number, };

/**
 * Where an export has got to.
 *
 * The order is the order phases run in, and the phase *before* a long one is the useful signal:
 * a UI that shows "typesetting 4,245 pages" for 45 seconds is telling the truth, and one that
 * shows a spinner is not.
 */
export type ExportPhase = "translating" | "readingAssets" | "layout" | "serializing" | "done" | "cancelled" | "failed";

/**
 * One progress report.
 */
export type ExportProgress = { 
/**
 * Which export this is about.
 *
 * Carried on every report because a user can start a second export while the first is still
 * running -- the window is not modal over the document -- and a status line that showed the
 * first job's phase during the second job's would be actively misleading.
 */
job_id: string, phase: ExportPhase, 
/**
 * Milliseconds since the export started. A `number`, not a `bigint`: `ts-rs` emits `bigint`
 * for a `u128` unless told otherwise, and a millisecond count is a `number`.
 */
elapsed_ms: number, 
/**
 * Anything worth saying beyond the phase. Empty for the common case.
 */
message: string, };

/**
 * What an export produced, as the frontend sees it.
 *
 * The timings are here so a caller can show the cost without measuring it around the call, and
 * so a slow export can be attributed: `translate_ms` is this codebase's share and the other two
 * are Typst's. That split matters because they differ by three orders of magnitude.
 */
export type ExportReply = { 
/**
 * Which document was exported. Echoed so a caller that started two can tell them apart.
 */
document_id: string, 
/**
 * The PDF bytes.
 */
pdf: Uint8Array, pages: number, 
/**
 * Milliseconds, as a JS `number` rather than `bigint`.
 *
 * `u128` is what Rust wants for a duration and what `ts-rs` would otherwise emit as
 * `bigint` — which is the same mistake as `order_key`, and the same fix. A millisecond
 * count is a `number`; nothing here reaches 2^53, and `bigint` in the generated type would
 * force every caller through `BigInt()` arithmetic to display it.
 */
elapsed_ms: number, translate_ms: number, layout_ms: number, serialize_ms: number, 
/**
 * Node types the translator had no rule for, whose text was exported unformatted.
 */
unknown_types: Array<string>, 
/**
 * Marks with no Typst equivalent, exported without the decoration.
 */
lossy_marks: Array<string>, 
/**
 * What Typst warned about. A warning is usually a *content* problem, so it belongs with the
 * document rather than in the terminal that ran the export.
 */
warnings: Array<string>, 
/**
 * A sentence naming what was lossy, or `None` when nothing was.
 */
lossy_summary: string | null, };

/**
 * One measured height, batched and debounced before crossing the bridge.
 *
 * A `ResizeObserver` can fire many times per second per section while the user
 * types. Batching and debouncing is what keeps that off the IPC path.
 */
export type HeightUpdate = { section_id: string, 
/**
 * Position in document order. Carried alongside the id because the geometry is
 * index-keyed, and resolving an id to an index on every batch would be a
 * lookup per update for no benefit.
 */
index: number, 
/**
 * Measured height in CSS pixels. Fractional, because
 * `getBoundingClientRect` is and rounding here would show as jitter.
 */
height: number, };

/**
 * A structural change to the document.
 *
 * Serialised as a tagged enum so the frontend can switch on `kind` without
 * guessing from which fields are present.
 */
export type LifecycleAction = { "kind": "split", section_id: string, at_block: number, index: number, } | { "kind": "merge", section_id: string, into_section_id: string, index: number, } | { "kind": "prune", section_id: string, previous_section_id: string, index: number, };

/**
 * The reply to a lifecycle action.
 *
 * Reports what actually happened rather than assuming the request succeeded: a
 * split that could not find a valid cut point comes back with
 * `applied: false`, and the frontend leaves the document as it is rather than
 * optimistically reconciling against a split that did not occur.
 */
export type LifecycleResult = { applied: boolean, 
/**
 * Section ids in the new order, when applied. The frontend replaces its
 * ordering wholesale rather than patching, because a split can move keys on
 * both sides of the cut.
 */
section_ids: Array<string>, 
/**
 * Why nothing happened, when `applied` is false.
 */
reason: string | null, };

/**
 * One row of the section manifest — the whole document as far as anything outside
 * the focused window is concerned.
 *
 * ~100 bytes per section, so a 2000-page document is ~50KB and the scrollbar,
 * outline and word counts are all cheap. Carries no content: that is the point.
 */
export type ManifestSection = { id: string, 
/**
 * Fractional index: a u64 with gaps, not a digit string. See
 * `holonomy_core::order` for why bare fractional digits are not a total
 * order.
 *
 * Typed as `number` rather than ts-rs's default `bigint` for `u64`, because that
 * default is *wrong here* rather than merely conservative.
 *
 * MessagePack has one unsigned integer type, and `@msgpack/msgpack` decodes it to
 * a JS `number` whenever the value fits in 53 bits -- which every real key does.
 * A declared `bigint` would then be a claim the wire does not honour, and the
 * first arithmetic on the field would be a type error against a `number` at
 * runtime. A type that says `bigint` over a value that is a `number` is worse
 * than either being consistent.
 *
 * The precision hazard is real but bounded, and bounded *by a test*:
 * `order::wire_precision_tests::order_keys_stay_exactly_representable` asserts
 * that the keys for four billion sections still fit in 53 bits. Reaching the
 * limit takes about 8.8 trillion sections; a 2000-page document is 667.
 */
order_key: number, title: string | null, word_count: number, mark_count: number, char_count: number, 
/**
 * Top-level block count. Not optional and not defaulted anywhere: it is the
 * difference between a height estimate accurate to ~5% and one 225% out, and
 * every write path in `holonomy_core` populates it.
 */
block_count: number, 
/**
 * Epoch milliseconds. `number`, not `bigint` -- see the note on `order_key`.
 *
 * ## Why the timestamps are `number` and not `bigint`
 *
 * Same reason as `order_key`: `rmp-serde` writes an `i64` as a MessagePack
 * 64-bit integer, and `@msgpack/msgpack` decodes it to a JS `number` whenever it
 * fits in 53 bits. Epoch milliseconds do -- 2^53 milliseconds is about 285,000
 * years -- so `bigint` would be a type the wire does not deliver.
 *
 * The bound is asserted rather than argued: `order::wire_precision_tests`
 * covers both the keys and the timestamps, because a contract whose numeric
 * types depend on a range nobody checks is a contract that breaks silently.
 */
created_at: number, updated_at: number, };

/**
 * What opening a path did.
 *
 * # Why three outcomes and not a bool
 *
 * Because the failure a user can hit is not an exception — it is "that file is a database
 * but not a document", and "there was nothing at that path, so a new document was
 * created". Those need different messages and the frontend cannot tell them apart from a
 * success. A bool would force it to re-derive the distinction from an error it may not
 * have been given, which is exactly the sort of inference that disagrees with the store on
 * a machine nobody tested.
 */
export type OpenDocumentReport = { document: DocumentSummary, 
/**
 * Where the document lives, so the title bar and "Save As…" can name it.
 */
path: string, 
/**
 * `existing` | `created` | `empty`.
 *
 * `empty` is its own case because an openable `.holo` with no documents in it is a
 * legitimate thing — a backup of an empty file, or a store the user has since cleared —
 * and reporting "opened your document" would be true and useless.
 */
kind: string, };

/**
 * What [`optimize_document`] reclaimed.
 *
 * Every field is measured rather than predicted, because the one a user can check by hand
 * is the file size in a file manager and a report that disagreed with it would be worse
 * than no report.
 *
 * # Why the counts are `number` and not `bigint`
 *
 * `ts-rs` maps Rust's 64-bit integers to `bigint`, which would force every caller to
 * compare against a `BigInt` literal and would make arithmetic in the notice line a
 * `BigInt` operation. The values are page counts and byte totals, so `i64` on the wire
 * would be exact anyway — but the *type* is the friction, not the width. `#[ts(type =
 * "number")]` keeps the generated contract honest about the fact that these are ordinary
 * counts, the same annotation `DocumentSummary::updated_at` already uses for the same
 * reason.
 */
export type OptimizeReport = { 
/**
 * Log rows folded before the sweep, without which an image deleted moments ago would
 * still look referenced.
 */
flushed: number, 
/**
 * Asset rows deleted.
 */
assetsDeleted: number, 
/**
 * Bytes those rows occupied.
 */
assetsFreed: number, 
/**
 * Database size in pages, before.
 */
pagesBefore: number, 
/**
 * Database size in pages, after.
 */
pagesAfter: number, 
/**
 * `pages_before - pages_after`, clamped at zero.
 *
 * Distinct from `assets_freed` on purpose: asset bytes are *content* removed, while
 * this is *space returned*. An image freed from the middle of the file is fully
 * removed and returns none, and conflating the two would promise a shrink the file
 * does not deliver. See [`optimize_document`].
 */
pagesReclaimed: number, 
/**
 * Bytes left in the `-wal` sidecar. Zero after a successful run.
 */
walBytes: number, };

/**
 * One section that matched a search, with enough context to show it.
 *
 * Section-level, not match-level, and that is a deliberate limit rather than a missing
 * feature. `holonomy-core`'s `SearchHit` is also section-level; the two are one row per
 * section, not per occurrence. What a user wants from a find is "which section is this
 * in and what does it say", and the frontend's job is to take them there.
 *
 * The occurrence *offset* is absent because the contentless FTS5 index cannot produce
 * one: it stores tokens, not character positions, and FTS5 exposes
 * `highlight()`/`snippet()` offsets for a contentless table over its own column -- which
 * is exactly the text this schema stopped storing twice. The frontend therefore places
 * the caret by searching the section's own text for the query, which it has anyway.
 */
export type SearchHit = { 
/**
 * The section to navigate to. The frontend scrolls this into the window and focuses
 * it; it does not need to know the section's position in the document, because the
 * geometry is the only thing that knows that and it already does.
 */
section_id: string, 
/**
 * Context around the match with `<b>` around the matched text.
 *
 * HTML, not a list of runs. FTS5's own `snippet()` emits HTML for the same purpose
 * and did so before the contentless move replaced it; a structured
 * `{before, match, after}` triple would be marginally safer to render and costs a
 * second type on the bridge for a string the backend already formatted.
 */
snippet: string, 
/**
 * bm25 relevance; lower is better.
 */
score: number, };

/**
 * The result of a search, with enough context for the UI to explain itself.
 */
export type SearchResponse = { hits: Array<SearchHit>, 
/**
 * How many sections matched in total, before `limit` was applied.
 *
 * Carried because "showing 20 of 340" and "showing all 20" are different
 * situations, and a truncated list that does not say so reads as a complete answer.
 */
total: number, };

/**
 * One section's content, fetched on demand.
 *
 * The same shape as the boot payload's `visible` entries, deliberately: a section
 * fetched later must be indistinguishable from one fetched at boot, or the frontend
 * would need two decode paths and one of them would go untested until a user scrolled
 * past the boot window.
 */
export type SectionContent = { id: string, 
/**
 * zstd-compressed ProseMirror JSON.
 *
 * # `serde_bytes` is load-bearing, and its absence was a real bug
 *
 * `rmp-serde` serialises a plain `Vec<u8>` as a MessagePack **array of numbers**,
 * not as a MessagePack `bin`. `@msgpack/msgpack` therefore decoded it to
 * `number[]`, and both frontend decoders — which check
 * `instanceof Uint8Array` and throw rather than repair — refused it.
 *
 * So the boot payload's content had *never* decoded. It went unnoticed for a
 * specific and unpleasant reason: `app/test/boot.ts` encodes its own fixture with
 * `@msgpack/msgpack`'s `encode`, which writes a `Uint8Array` as `bin`. The test
 * therefore agreed with itself and with neither the real encoder nor the real
 * decoder. The in-engine verification found it, on the first run where a payload
 * carrying section content came off the bridge — and the message it produced named
 * the symptom precisely while the cause was three layers down.
 *
 * `serde_bytes` makes `rmp-serde` emit `bin`. It is also what makes the choice of
 * MessagePack worth having: a 7KB section is 7KB on the wire as `bin`, and roughly
 * 30KB as an array of small integers — which is larger than the JSON it replaced,
 * defeating the entire argument for a binary format on this one field.
 *
 * `#[serde(with = ...)]` and `#[ts(type = ...)]` are both needed and say different
 * things: the first is what the encoder does, the second is what the generated
 * TypeScript says. A type annotation cannot change a wire format, and it was the
 * `#[ts]` half that existed when this broke.
 */
content_zstd: Uint8Array, };
