#!/usr/bin/env python3
"""Regenerate `crates/holonomy-assets/src/payload.rs` from `assets/generated/fonts.json`.

`build_font_payload.py` writes the blob and the manifest; this writes the Rust that names them. They
are separate because the blob is data and the Rust is code, and hand-editing one to match the other is
how they drift. The Rust file is a checked-in artefact -- `include_bytes!` needs a real file -- so
"generated" here means *derived*, not *computed at build time*: nothing in the build runs this, and no
constant in the payload is generated while a gate runs.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "generated" / "fonts.json"
OUT = ROOT / "crates" / "holonomy-assets" / "src" / "payload.rs"

# The hand-written tail of `payload.rs`, preserved verbatim across regenerations. It documents a bug
# that Phase 8 introduced (a duplicate `build_atlas` that silently dropped the boot timings), and a
# generated file that drops a note like that is how the bug gets reintroduced.
TAIL = ROOT / "tools" / "payload_tail.rs"
TAIL_PATH = TAIL

HEADER = '''//! Generated by `tools/build_font_payload.py` and `tools/emit_payload_rs.py`. Do not edit.
//!
//! Regenerate with:
//!
//! ```sh
//! python3 tools/build_font_payload.py && python3 tools/emit_payload_rs.py
//! ```
//!
//! The build fails if this file is missing, so the payload cannot be silently dropped; see
//! `build.rs` for the size assertion and `tests/payload.rs` for the coverage gate.
//!
//! # Five faces, and why the fifth is a different font
//!
//! Four are Inter (regular, bold, italic) and JetBrains Mono. The fifth is **Noto Sans Math**, added by
//! Phase 9B, and it is a separate face rather than a fourth Inter weight for a reason recorded in
//! PROJECT.md §2.9.2: the alternatives -- STIX Two Math especially -- ship **CFF outlines**, and
//! reading CFF means carrying a CFF interpreter, which is not 60 KiB. Noto Sans Math is TrueType, so
//! `ttf_parser`, already a dependency for the other four, reads it with nothing new.
//!
//! It is also the only face that carries Greek and Mathematical Operators. Inter has neither, so a
//! Greek letter typed into a document would have rasterised as .notdef -- a hollow box, which reads as
//! a missing glyph rather than as a missing feature.
//!
//! # What is deliberately *not* here
//!
//! * **Box Drawing 0x2500..0x257F** -- procedural, in `box_drawing.rs`. Inter ships no Box Drawing
//!   glyphs, and the font's own would round poorly at cell boundaries and show antialiasing gaps where
//!   two of them meet.
//! * **The radical and the fraction bar** -- procedural, in `math.rs`. Both are rectangles: a 1--2 px
//!   horizontal fill and an L-shaped tick with an overline. Drawing a rectangle from a glyph outline
//!   means antialiasing two edges that are supposed to meet exactly, and paying for the glyph.
//! * **Layout scripts (GSUB/GPOS/GDEF)** -- there is no shaping. Codepoint to glyph, one glyph per
//!   character.
'''

STYLE_DOC = {
    "Regular": "    /// Regular text.",
    "Bold": "    /// Bold text.",
    "Italic": "    /// Italic text.",
    "Monospace": "    /// Monospace text.",
    "Math": "    /// Math symbols: Greek and Mathematical Operators, from Noto Sans Math.",
}

STYLE_ARM = {
    "Regular": "    Regular = 0,",
    "Bold": "    Bold = 1,",
    "Italic": "    Italic = 2,",
    "Monospace": "    Monospace = 3,",
    "Math": "    Math = 4,",
}


def main() -> int:
    m = json.loads(MANIFEST.read_text())
    faces = m["faces"]
    out: list[str] = [HEADER]

    out.append(
        f'/// The compressed font payload: all {len(faces)} faces concatenated, then brotli\'d as one '
        "stream.\n"
        "///\n"
        "/// One stream rather than many because the faces share table layouts, glyph names and many\n"
        "/// near-identical outlines. Decompressing yields one contiguous buffer that [`FACES`] slices\n"
        "/// into faces with no copying."
    )
    out.append(
        'pub const PACKED_FONTS: &[u8] = '
        'include_bytes!("../../../assets/generated/fonts.bin.br");\n'
    )

    out.append("/// One face within [`PACKED_FONTS`], located by offset into the decompressed buffer.")
    out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
    out.append("pub struct FaceEntry {")
    out.append("    /// Human-readable name, for diagnostics and the coverage report.")
    out.append("    pub name: &'static str,")
    out.append("    /// Style this face provides.")
    out.append("    pub style: Style,")
    out.append("    /// Whether advances are uniform. Drives line layout and box-drawing geometry.")
    out.append("    pub monospace: bool,")
    out.append("    /// Byte offset within the decompressed buffer.")
    out.append("    pub offset: u32,")
    out.append("    /// Byte length within the decompressed buffer.")
    out.append("    pub length: u32,")
    out.append("}\n")

    out.append("/// Style, as referenced by the UI and by the atlas key.")
    out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]")
    out.append("#[repr(u8)]")
    out.append("pub enum Style {")
    for f in faces:
        out.append(STYLE_DOC[f["style"]])
        out.append(STYLE_ARM[f["style"]])
    out.append("}\n")

    out.append(f"/// Total decompressed size, {m['raw_len']:,} bytes.")
    out.append(f"pub const RAW_LEN: usize = {m['raw_len']};\n")

    out.append(f"/// The {len(faces)} faces, in atlas order.")
    out.append(f"pub const FACES: [FaceEntry; {len(faces)}] = [")
    for f in faces:
        out.append("    FaceEntry {")
        out.append(f"        name: \"{f['name']}\",")
        out.append(f"        style: Style::{f['style']},")
        out.append(f"        monospace: {'true' if f['monospace'] else 'false'},")
        out.append(f"        offset: {f['offset']},")
        out.append(f"        length: {f['length']},")
        out.append("    },")
    out.append("];\n")

    out.append("/// Compressed size, asserted by `build.rs`.")
    out.append(f"pub const PACKED_LEN: usize = {m['packed_len']};\n")
    out.append("/// Digest of the compressed stream, so a regenerated payload cannot differ silently.")
    out.append(f'pub const PACKED_SHA256: &str = "{m["packed_sha256"]}";\n')
    out.append("/// Digest of the decompressed buffer.")
    out.append(f'pub const RAW_SHA256: &str = "{m["raw_sha256"]}";\n')

    out.append("/// Codepoint ranges taken from the text faces.")
    out.append(f"pub const TEXT_RANGES: [(u32, u32); {len(m['text_ranges'])}] = [")
    for lo, hi in m["text_ranges"]:
        out.append(f"    (0x{lo:02X}, 0x{hi:02X}),")
    out.append("];\n")

    out.append("/// Codepoint ranges taken from the math face. Phase 9B.")
    out.append(f"pub const MATH_RANGES: [(u32, u32); {len(m['math_ranges'])}] = [")
    for lo, hi in m["math_ranges"]:
        out.append(f"    (0x{lo:03X}, 0x{hi:03X}),")
    out.append("];\n")

    out.append("/// Box Drawing, which is procedural and deliberately absent from every face.")
    out.append("pub const BOX_RANGE: (u32, u32) = (0x2500, 0x257F);\n")

    out.append("/// The compressed payload's budget in bytes, asserted by `build.rs`.")
    out.append(f"pub const PACKED_BUDGET: usize = {m.get('packed_budget', 81920)};\n")

    out.append("/// Every codepoint the text faces are expected to carry.")
    out.append("pub fn codepoints_in_text_ranges() -> impl Iterator<Item = u32> {")
    out.append("    TEXT_RANGES")
    out.append("        .iter()")
    out.append("        .flat_map(|&(lo, hi)| lo..=hi)")
    out.append("}\n")

    out.append("/// Every codepoint the math face is expected to carry.")
    out.append("pub fn codepoints_in_math_ranges() -> impl Iterator<Item = u32> {")
    out.append("    MATH_RANGES")
    out.append("        .iter()")
    out.append("        .flat_map(|&(lo, hi)| lo..=hi)")
    out.append("}\n")

    out.append("/// True when `codepoint` is one the math face carries, and so must be drawn in [`Style::Math`].")
    out.append("///")
    out.append("/// The other half of [`MATH_RANGES`]'s job. `MATH_RANGES` says what to *subset*; this says")
    out.append("/// what to *draw in the math style*, and a renderer needs the second without re-walking the")
    out.append("/// ranges on every glyph.")
    out.append("///")
    out.append("/// It matters because the math face deliberately does **not** carry ASCII. A formula's variables")
    out.append("/// -- `x`, `b`, the `2` in `2a` -- are ASCII codepoints, and they are drawn from the text faces")
    out.append("/// (`Italic` for a letter, by the convention every textbook uses) while `\\alpha` and `\\sum` come")
    out.append("/// from the math face. So the style for each glyph is a real decision with a real answer, and")
    out.append("/// this function is that answer.")
    out.append("///")
    out.append("/// Linear over ten ranges, called once per glyph of a formula and never for a text glyph, which")
    out.append("/// is why it is not worth a lookup table.")
    out.append("pub fn is_math_symbol(codepoint: u32) -> bool {")
    out.append("    MATH_RANGES")
    out.append("        .iter()")
    out.append("        .any(|&(lo, hi)| codepoint >= lo && codepoint <= hi)")
    out.append("}\n")

    out.append("/// Every codepoint from every face, **plus** the procedural Box Drawing range.")
    out.append("///")
    out.append("/// The Box Drawing chain is here even though no face carries those codepoints, and that is")
    out.append("/// the point: the atlas is built for the union of what is rasterised from fonts and what is")
    out.append("/// drawn procedurally, so the ranges a caller must be able to *address* include both. Phase")
    out.append("/// 9B's first regeneration dropped this chain, and `every_required_codepoint_resolves_in_every_face`")
    out.append("/// immediately reported 497 codepoints where it expected 625 -- the 128 Box Drawing slots")
    out.append("/// simply had no index. A generated file that quietly loses a function is why this script")
    out.append("/// exists rather than the Rust being hand-edited in the other direction.")
    out.append("pub fn codepoints_all() -> impl Iterator<Item = u32> {")
    out.append("    codepoints_in_text_ranges()")
    out.append("        .chain(codepoints_in_math_ranges())")
    out.append("        .chain(BOX_RANGE.0..=BOX_RANGE.1)")
    out.append("}")

    # The hand-written tail of the old file. A generator that rewrites the whole file must either
    # reproduce this or fail loudly; silently dropping a 20-line note about a duplicated `build_atlas`
    # that once cost a boot measurement is not an option.
    tail = TAIL_PATH.read_text() if TAIL_PATH.exists() else ""
    if tail.strip():
        out.append("")
        out.append(tail.rstrip())

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(faces)} faces, {m['packed_len']:,} B packed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
