//! Generated by `tools/build_font_payload.py` and `tools/emit_payload_rs.py`. Do not edit.
//!
//! Regenerate with:
//!
//! ```sh
//! python3 tools/build_font_payload.py && python3 tools/emit_payload_rs.py
//! ```
//!
//! The build fails if this file is missing, so the payload cannot be silently dropped; see
//! `build.rs` for the size assertion and `tests/payload.rs` for the coverage gate.
//!
//! # Five faces, and why the fifth is a different font
//!
//! Four are Inter (regular, bold, italic) and JetBrains Mono. The fifth is **Noto Sans Math**, added by
//! Phase 9B, and it is a separate face rather than a fourth Inter weight for a reason recorded in
//! PROJECT.md §2.9.2: the alternatives -- STIX Two Math especially -- ship **CFF outlines**, and
//! reading CFF means carrying a CFF interpreter, which is not 60 KiB. Noto Sans Math is TrueType, so
//! `ttf_parser`, already a dependency for the other four, reads it with nothing new.
//!
//! It is also the only face that carries Greek and Mathematical Operators. Inter has neither, so a
//! Greek letter typed into a document would have rasterised as .notdef -- a hollow box, which reads as
//! a missing glyph rather than as a missing feature.
//!
//! # What is deliberately *not* here
//!
//! * **Box Drawing 0x2500..0x257F** -- procedural, in `box_drawing.rs`. Inter ships no Box Drawing
//!   glyphs, and the font's own would round poorly at cell boundaries and show antialiasing gaps where
//!   two of them meet.
//! * **The radical and the fraction bar** -- procedural, in `math.rs`. Both are rectangles: a 1--2 px
//!   horizontal fill and an L-shaped tick with an overline. Drawing a rectangle from a glyph outline
//!   means antialiasing two edges that are supposed to meet exactly, and paying for the glyph.
//! * **Layout scripts (GSUB/GPOS/GDEF)** -- there is no shaping. Codepoint to glyph, one glyph per
//!   character.

/// The compressed font payload: all 5 faces concatenated, then brotli'd as one stream.
///
/// One stream rather than many because the faces share table layouts, glyph names and many
/// near-identical outlines. Decompressing yields one contiguous buffer that [`FACES`] slices
/// into faces with no copying.
pub const PACKED_FONTS: &[u8] = include_bytes!("../../../assets/generated/fonts.bin.br");

/// One face within [`PACKED_FONTS`], located by offset into the decompressed buffer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FaceEntry {
    /// Human-readable name, for diagnostics and the coverage report.
    pub name: &'static str,
    /// Style this face provides.
    pub style: Style,
    /// Whether advances are uniform. Drives line layout and box-drawing geometry.
    pub monospace: bool,
    /// Byte offset within the decompressed buffer.
    pub offset: u32,
    /// Byte length within the decompressed buffer.
    pub length: u32,
}

/// Style, as referenced by the UI and by the atlas key.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(u8)]
pub enum Style {
    /// Regular text.
    Regular = 0,
    /// Bold text.
    Bold = 1,
    /// Italic text.
    Italic = 2,
    /// Monospace text.
    Monospace = 3,
    /// Math symbols: Greek and Mathematical Operators, from Noto Sans Math.
    Math = 4,
}

/// Total decompressed size, 169,480 bytes.
pub const RAW_LEN: usize = 169480;

/// The 5 faces, in atlas order.
pub const FACES: [FaceEntry; 5] = [
    FaceEntry {
        name: "Inter-Regular",
        style: Style::Regular,
        monospace: false,
        offset: 0,
        length: 24188,
    },
    FaceEntry {
        name: "Inter-Bold",
        style: Style::Bold,
        monospace: false,
        offset: 24188,
        length: 24384,
    },
    FaceEntry {
        name: "Inter-Italic",
        style: Style::Italic,
        monospace: false,
        offset: 48572,
        length: 24952,
    },
    FaceEntry {
        name: "JetBrainsMono-Regular",
        style: Style::Monospace,
        monospace: true,
        offset: 73524,
        length: 23680,
    },
    FaceEntry {
        name: "NotoSansMath-Regular",
        style: Style::Math,
        monospace: false,
        offset: 97204,
        length: 72276,
    },
];

/// Compressed size, asserted by `build.rs`.
pub const PACKED_LEN: usize = 78354;

/// Digest of the compressed stream, so a regenerated payload cannot differ silently.
pub const PACKED_SHA256: &str = "f32aacc36f8e338f4eee969349359ea1d6dd20e1cb136f7ddb3a205db04273ef";

/// Digest of the decompressed buffer.
pub const RAW_SHA256: &str = "a1910d25dc42390b53d5297a33522fced14f60ae57a35fd135eddec6fdf30d42";

/// Codepoint ranges taken from the text faces.
pub const TEXT_RANGES: [(u32, u32); 2] = [(0x20, 0x7E), (0xA0, 0xFF)];

/// Codepoint ranges taken from the math face. Phase 9B.
pub const MATH_RANGES: [(u32, u32); 7] = [
    (0x0B1, 0x0B1),
    (0x0D7, 0x0D7),
    (0x0F7, 0x0F7),
    (0x2190, 0x21FF),
    (0x391, 0x3A9),
    (0x3B1, 0x3C9),
    (0x2200, 0x22FF),
];

/// Box Drawing, which is procedural and deliberately absent from every face.
pub const BOX_RANGE: (u32, u32) = (0x2500, 0x257F);

/// The compressed payload's budget in bytes, asserted by `build.rs`.
pub const PACKED_BUDGET: usize = 81920;

/// Every codepoint the text faces are expected to carry.
pub fn codepoints_in_text_ranges() -> impl Iterator<Item = u32> {
    TEXT_RANGES.iter().flat_map(|&(lo, hi)| lo..=hi)
}

/// Every codepoint the math face is expected to carry.
pub fn codepoints_in_math_ranges() -> impl Iterator<Item = u32> {
    MATH_RANGES.iter().flat_map(|&(lo, hi)| lo..=hi)
}

/// Every codepoint from every face, **plus** the procedural Box Drawing range.
///
/// The Box Drawing chain is here even though no face carries those codepoints, and that is
/// the point: the atlas is built for the union of what is rasterised from fonts and what is
/// drawn procedurally, so the ranges a caller must be able to *address* include both. Phase
/// 9B's first regeneration dropped this chain, and `every_required_codepoint_resolves_in_every_face`
/// immediately reported 497 codepoints where it expected 625 -- the 128 Box Drawing slots
/// simply had no index. A generated file that quietly loses a function is why this script
/// exists rather than the Rust being hand-edited in the other direction.
pub fn codepoints_all() -> impl Iterator<Item = u32> {
    codepoints_in_text_ranges()
        .chain(codepoints_in_math_ranges())
        .chain(BOX_RANGE.0..=BOX_RANGE.1)
}

// NOTE: an earlier version of Phase 8 added a `build_atlas` *here*, duplicating
// [`crate::build_atlas`]. That was wrong twice over. It returned `Atlas` where the real one returns
// `(Atlas, BootReport)`, so every caller silently dropped the phase timings -- including the one that
// measures boot. And it decompressed into a plain `Vec<u8>` where the real one decompresses into a
// page-locked, `mlock`ed, zeroizing `SecureBlock`, which is the entire point of Phase 4's
// one-time pass: the expanded fonts are *supposed* to be scrubbed, and the duplicate made them
// ordinary heap that a later `Drop` would leave behind.
//
// There is one `build_atlas`. It lives at the crate root because it is the whole pass, not a
// payload detail, and it is the only place that knows the phases have to happen in order.
