//! Generated by `tools/build_font_payload.py`. Do not edit.
//!
//! Regenerate with:
//!
//! ```sh
//! python3 tools/build_font_payload.py
//! ```
//!
//! The build fails if this file is missing, so the payload cannot be silently dropped; see
//! `build.rs` for the size assertion and `tests/payload.rs` for the coverage gate.

/// The compressed font payload: all faces concatenated, then brotli'd as one stream.
///
/// One stream rather than four because the faces share table layouts, glyph names and many
/// near-identical outlines: measured at 45,327 B joined against 56,713 B compressed
/// independently, a 20% saving. Decompressing yields one contiguous buffer that
/// [`FACES`] slices into four [`ttf_parser::Face`]s with no copying.
pub const PACKED_FONTS: &[u8] = include_bytes!("../../../assets/generated/fonts.bin.br");

/// One face within [`PACKED_FONTS`], located by offset into the decompressed buffer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FaceEntry {
    /// Human-readable name, for diagnostics and the coverage report.
    pub name: &'static str,
    /// Style this face provides.
    pub style: Style,
    /// Whether advances are uniform. Drives line layout and box-drawing geometry.
    pub monospace: bool,
    /// Byte offset within the decompressed buffer.
    pub offset: u32,
    /// Byte length within the decompressed buffer.
    pub length: u32,
}

/// Style, as referenced by the UI and by the atlas key.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Style {
    /// Regular text.
    Regular = 0,
    /// Bold text.
    Bold = 1,
    /// Italic text.
    Italic = 2,
    /// Monospace text.
    Monospace = 3,
}

/// Total decompressed size, 97,204 bytes.
pub const RAW_LEN: usize = 97204;

/// The four faces, in atlas order.
pub const FACES: [FaceEntry; 4] = [
    FaceEntry {
        name: "Inter-Regular",
        style: Style::Regular,
        monospace: false,
        offset: 0,
        length: 24188,
    },
    FaceEntry {
        name: "Inter-Bold",
        style: Style::Bold,
        monospace: false,
        offset: 24188,
        length: 24384,
    },
    FaceEntry {
        name: "Inter-Italic",
        style: Style::Italic,
        monospace: false,
        offset: 48572,
        length: 24952,
    },
    FaceEntry {
        name: "JetBrainsMono-Regular",
        style: Style::Monospace,
        monospace: true,
        offset: 73524,
        length: 23680,
    },
];

/// sha256 of the compressed payload, asserted at build time against the file.
pub const PACKED_SHA256: &str = "26393943c298ac88af8ae6fb812afa26272d725f8ec0c7084226655c3ceed89f";

/// sha256 of the decompressed payload. Checked by the round-trip test.
pub const RAW_SHA256: &str = "9040f39475bedca5d436c8b68f8cba733b91962f77564fe002ed6a1bdcecb75f";

/// Codepoint ranges taken from the fonts: ASCII and Latin-1 Supplement.
pub const TEXT_RANGES: [(u32, u32); 2] = [(0x20, 0x7E), (0xA0, 0xFF)];

/// Box Drawing, generated procedurally at boot and therefore absent from the payload.
pub const BOX_RANGE: (u32, u32) = (0x2500, 0x257F);

/// Compressed size budget for [`PACKED_FONTS`].
///
/// Raised from 45 KiB to 80 KiB by explicit decision: at four faces and 319
/// codepoints the outline data alone does not compress below 45 KiB, and the binary
/// still has roughly 2.1 MiB of headroom under the 2.5 MiB ceiling, so the tighter
/// number was constraining nothing it was meant to protect. The measured payload is
/// 45,327 B.
pub const PACKED_BUDGET: usize = 81920;

/// Every codepoint the fonts supply: ASCII 0x20..0x7E and Latin-1 0xA0..0xFF.
///
/// Returned fresh each call so a caller cannot mutate shared state. Called once per face per
/// size at boot, which is 4 x 2 times, so the allocation does not matter; the alternative is
/// a `static` slice behind a lock for no benefit.
pub fn codepoints_in_text_ranges() -> impl Iterator<Item = u32> {
    TEXT_RANGES.iter().flat_map(|&(lo, hi)| lo..=hi)
}

/// The full required coverage: the font ranges plus Box Drawing.
pub fn codepoints_all() -> impl Iterator<Item = u32> {
    codepoints_in_text_ranges().chain(BOX_RANGE.0..=BOX_RANGE.1)
}

/// Decompress [`PACKED_FONTS`] into the TTF bytes.
///
/// The one place the packed blob is expanded, so a caller that wants a [`crate::atlas::Atlas`] does
/// not have to know that the fonts are brotli-compressed, nor that `brotli_decompressor` is a
/// dependency for exactly this. Returns the buffer rather than a guard so the `Face<'_>` borrows it
/// can be held for as long as the caller needs.
pub fn unpack_fonts() -> Result<Vec<u8>, crate::Error> {
    use std::io::Read as _;
    let mut input = std::io::Cursor::new(PACKED_FONTS);
    let mut raw = Vec::with_capacity(RAW_LEN);
    brotli_decompressor::Decompressor::new(&mut input, 4096).read_to_end(&mut raw)?;
    Ok(raw)
}

/// The whole atlas: every face, every codepoint, every size.
///
/// Phase 8. Before this, every caller that wanted to draw anything had to open a `crate::atlas::AtlasBuilder`,
/// loop over [`FACES`], parse each face with `ttf_parser`, call [`crate::raster::rasterize_face`],
/// and call `finish` -- which is fifteen lines of ceremony repeated in every test that wanted a pixel.
/// The dependencies needed for it (`ttf-parser`, `brotli-decompressor`) are *this crate's*, so the
/// ceremony belongs here too.
///
/// # What lands in the atlas
///
/// [`codepoints_all`](codepoints_all): both text ranges plus the whole box-drawing block, for every
/// face, at every size. That is [`crate::metric::CODEPOINTS`] codepoints times [`FACES`]::len()
/// times `sizes.len()` glyphs, and the builder enforces
/// [`PACKED_BUDGET`](crate::payload::PACKED_BUDGET) worth of *packed* size -- so asking for too many
/// sizes fails here rather than producing an atlas that silently overflows the 2.5 MiB binary budget.
///
/// # Errors
///
/// [`crate::Error`], which covers a decompression failure, an unparseable face, a glyph the builder
/// refuses, and a budget overflow. None of them are recoverable at the call site, and all of them are
/// better as one error than as four.
pub fn build_atlas(sizes: &[u16]) -> Result<crate::atlas::Atlas, crate::Error> {
    use ttf_parser::Face as TtfFace;

    let raw = unpack_fonts()?;
    let mut builder = crate::atlas::AtlasBuilder::new(sizes)?;
    for entry in FACES {
        let slice = &raw[entry.offset as usize..(entry.offset + entry.length) as usize];
        let index = FACES.iter().position(|f| f.name == entry.name).unwrap_or(0) as u32;
        let face = TtfFace::parse(slice, 0).map_err(|e| crate::Error::Parse {
            index,
            detail: format!("{e}"),
        })?;
        crate::raster::rasterize_face(&face, &entry, sizes, &mut builder)?;
    }
    // Box drawing is *procedural*, not from a font: `draw_glyph` emits each rune's arms from the
    // verified table. Rasterising them from the font instead would work but would make the chrome's
    // rules depend on a font's box-drawing glyphs being present and correctly weighted -- and the
    // whole point of the table is that they are not the font's to decide.
    crate::box_drawing::add_box_drawing(sizes, &mut builder)?;
    Ok(builder.finish()?.0)
}
